
 
CREATE TABLE  "BOOK" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(100), 
	"PRICE" NUMBER(8,2), 
	 PRIMARY KEY ("ID") ENABLE
   )
/


 
CREATE TABLE  "CUSTOMER" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20), 
	"PASSWORD" VARCHAR2(20), 
	"ZIP" VARCHAR2(20), 
	"ADDRESS" VARCHAR2(50), 
	"TELEPHONE" VARCHAR2(20), 
	"EMAIL" VARCHAR2(30), 
	 PRIMARY KEY ("ID") ENABLE
   )
/

CREATE TABLE  "ORDERFORM" 
   (	"ID" NUMBER, 
	"COST" NUMBER(8,2), 
	"ORDERDATE" DATE, 
	"CUSTOMERID" NUMBER, 
	 PRIMARY KEY ("ID") ENABLE, 
	 FOREIGN KEY ("CUSTOMERID")
	  REFERENCES  "CUSTOMER" ("ID") ENABLE
   )
/

CREATE TABLE  "ORDERLINE" 
   (	"ID" NUMBER, 
	"NUM" NUMBER NOT NULL ENABLE, 
	"ORDERID" NUMBER, 
	"BOOKID" NUMBER, 
	 PRIMARY KEY ("ID") ENABLE, 
	 FOREIGN KEY ("ORDERID")
	  REFERENCES  "ORDERFORM" ("ID") ENABLE, 
	 FOREIGN KEY ("BOOKID")
	  REFERENCES  "BOOK" ("ID") ENABLE
   )
/